BEGIN;

INSERT INTO generator.fifa_league(name) values('3. Liga');
INSERT INTO generator.fifa_league(name) values('3F Superliga');
INSERT INTO generator.fifa_league(name) values('Allsvenskan');
INSERT INTO generator.fifa_league(name) values('Bundesliga');
INSERT INTO generator.fifa_league(name) values('Bundesliga 2');
INSERT INTO generator.fifa_league(name) values('CSL');
INSERT INTO generator.fifa_league(name) values('Calcio B');
INSERT INTO generator.fifa_league(name) values('Camp. AFP PlanVital');
INSERT INTO generator.fifa_league(name) values('Domino''s Ligue 2');
INSERT INTO generator.fifa_league(name) values('EFL Championship');
INSERT INTO generator.fifa_league(name) values('EFL League One');
INSERT INTO generator.fifa_league(name) values('EFL League Two');
INSERT INTO generator.fifa_league(name) values('Eliteserien');
INSERT INTO generator.fifa_league(name) values('Eredivisie');
INSERT INTO generator.fifa_league(name) values('Hyundai A-League');
INSERT INTO generator.fifa_league(name) values('K-League 1');
INSERT INTO generator.fifa_league(name) values('LIGA BBVA MX');
INSERT INTO generator.fifa_league(name) values('LaLiga Santander');
INSERT INTO generator.fifa_league(name) values('LaLiga SmartBank');
INSERT INTO generator.fifa_league(name) values('Libertadores');
INSERT INTO generator.fifa_league(name) values('Liga Dimayor');
INSERT INTO generator.fifa_league(name) values('Liga I');
INSERT INTO generator.fifa_league(name) values('Liga NOS');
INSERT INTO generator.fifa_league(name) values('Liga do Brasil');
INSERT INTO generator.fifa_league(name) values('Ligue 1 Conforama');
INSERT INTO generator.fifa_league(name) values('MBS Pro League');
INSERT INTO generator.fifa_league(name) values('MLS');
INSERT INTO generator.fifa_league(name) values('Meiji Yasuda J1');
INSERT INTO generator.fifa_league(name) values('PKO Ekstraklasa');
INSERT INTO generator.fifa_league(name) values('Premier League');
INSERT INTO generator.fifa_league(name) values('Pro League');
INSERT INTO generator.fifa_league(name) values('RSL');
INSERT INTO generator.fifa_league(name) values('Resto del mundo');
INSERT INTO generator.fifa_league(name) values('SAF');
INSERT INTO generator.fifa_league(name) values('SSE Airtricity Lge');
INSERT INTO generator.fifa_league(name) values('Scottish Prem');
INSERT INTO generator.fifa_league(name) values('Serie A TIM');
INSERT INTO generator.fifa_league(name) values('Sudamericana');
INSERT INTO generator.fifa_league(name) values('Süper Lig');
INSERT INTO generator.fifa_league(name) values('Ö. Bundesliga');

COMMIT;