version: "3"
services:
  database:
    image: postgres:10.10-alpine
    container_name: fifa_gen_dev_db
    ports:
      - "127.0.0.1:5431:5432"
    environment:
      POSTGRES_USER: fifa_gen_dev
      POSTGRES_PASSWORD: fifa_gen_dev
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: fifa
